wandb_version: 1

env:
  desc: null
  value: InvertedPendulum-v4
hid:
  desc: null
  value: 400
l:
  desc: null
  value: 2
gamma:
  desc: null
  value: 0.99
seed:
  desc: null
  value: 123
cpu:
  desc: null
  value: 4
steps:
  desc: null
  value: 4000
epochs:
  desc: null
  value: 50
exp_name:
  desc: null
  value: ppo
experiment_no:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1734110755.0
    t:
      1:
      - 1
      - 2
      - 3
      - 53
      - 55
      - 105
      2:
      - 1
      - 2
      - 3
      - 53
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
