wandb_version: 1

env_name:
  desc: null
  value: InvertedPendulum-v4
agent:
  desc: null
  value: PPO
mode:
  desc: null
  value: train
gamma:
  desc: null
  value: 0.99
seed:
  desc: null
  value: 123
K:
  desc: null
  value: 32
max_buffer_size:
  desc: null
  value: 100000
training_batch_size:
  desc: null
  value: 32
max_training_steps:
  desc: null
  value: 70000
max_episode_length:
  desc: null
  value: 1000
warm_up_steps:
  desc: null
  value: 200
model_saving_interval:
  desc: null
  value: 5000
do_not_save:
  desc: null
  value: false
do_not_load:
  desc: null
  value: true
evaluate_interval:
  desc: null
  value: 2000
visualize:
  desc: null
  value: false
evaluate_num_episodes:
  desc: null
  value: 20
debug:
  desc: null
  value: false
cuda:
  desc: null
  value: cuda:0
max_training_hours:
  desc: null
  value: 0
cpu:
  desc: null
  value: false
save_path:
  desc: null
  value: ''
env_num:
  desc: null
  value: 16
memory_step_length:
  desc: null
  value: 8
level_idx:
  desc: null
  value: 1
state_mode:
  desc: null
  value: 5
action_mode:
  desc: null
  value: 0
reward_mode:
  desc: null
  value: 2
terminal_mode:
  desc: null
  value: 0
train_multiple_levels:
  desc: null
  value: false
multiple_level_start:
  desc: null
  value: 1
multiple_level_end:
  desc: null
  value: 50
max_demo_episodes:
  desc: null
  value: 50
enable_concentration:
  desc: null
  value: false
concentration_count:
  desc: null
  value: 4
cooldown_count:
  desc: null
  value: 8
train_count:
  desc: null
  value: 1
eval_num:
  desc: null
  value: 100
do_not_post:
  desc: null
  value: false
code_version:
  desc: null
  value: 1.1.0
env_extra_dict:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1734031390.0
    t:
      1:
      - 1
      - 2
      - 3
      - 53
      - 55
      - 105
      2:
      - 1
      - 2
      - 3
      - 53
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
